FROM debian:latest

COPY . .

ENV PORT=${PORT}
ENV OWNER_ID=${OWNER_ID}
ENV TOKEN=${TOKEN}
ENV MANAGER_GUILD=${MANAGER_GUILD}
ENV GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
ENV CLIENT_SECRET=${CLIENT_SECRET}
ENV CLIENT_ID=${CLIENT_ID}
ENV DATABASE_URL=${DATABASE_URL}

EXPOSE ${PORT}

RUN apt update && apt install -y python3 python3-pip && pip install -r requirements.txt
